#!/usr/bin/env python3

import time
import sys

# Na początku dodam zmienne pytające o: kraj, miasto, godzinę

print("##############################")
print("#    program adamskiego      #")
print("#  do sprawdzania pogody     #")
print("##############################")

print("chcesz sprawdzić pogodę?")
zapytanie = input("tak/nie")
if zapytanie == "nie":
    print("zamykanie programu za:")
    time.sleep(0.5)
    print("3")
    time.sleep(0.5)
    print("2")
    time.sleep(0.5)
    print("1")
    time.sleep(1)
    print("zamknięte!")
    sys.exit()
elif zapytanie == "tak":
    kraj = input("podaj swój kraj")
    print("Ładowanie 10%")
    time.sleep(0.5)
    print("Ładowanie 20%")
    time.sleep(0.5)
    print("Ładowanie 30%")
    time.sleep(0.5)
    print("Ładowanie 40%")
    time.sleep(0.5)
    print("Ładowanie 50%")
    time.sleep(0.5)
    print("Ładowanie 60%")
    time.sleep(0.5)
    print("Ładowanie 70%")
    time.sleep(0.5)
    print("Ładowanie 80%")
    time.sleep(0.5)
    print("Ładowanie 90%")
    time.sleep(0.5)
    print("Ładowanie 100%")
    time.sleep(0.5)
    print("znaleziono kraj!!!")

    miasto = input("podaj swoje miasto")

    print("Ładowanie 10%")
    time.sleep(0.5)
    print("Ładowanie 20%")
    time.sleep(0.5)
    print("Ładowanie 30%")
    time.sleep(0.5)
    print("Ładowanie 40%")
    time.sleep(0.5)
    print("Ładowanie 50%")
    time.sleep(0.5)
    print("Ładowanie 60%")
    time.sleep(0.5)
    print("Ładowanie 70%")
    time.sleep(0.5)
    print("Ładowanie 80%")
    time.sleep(0.5)
    print("Ładowanie 90%")
    time.sleep(0.5)
    print("Ładowanie 100%")
    time.sleep(0.5)
    print("znaleziono twoje miasto!!!")

    godzina = input("teraz podaj jeszcze tylko aktualną godzine!")

    print("Ładowanie 10%")
    time.sleep(0.5)
    print("Ładowanie 20%")
    time.sleep(0.5)
    print("Ładowanie 30%")
    time.sleep(0.5)
    print("Ładowanie 40%")
    time.sleep(0.5)
    print("Ładowanie 50%")
    time.sleep(0.5)
    print("Ładowanie 60%")
    time.sleep(0.5)
    print("Ładowanie 70%")
    time.sleep(0.5)
    print("Ładowanie 80%")
    time.sleep(0.5)
    print("Ładowanie 90%")
    time.sleep(0.5)
    print("Ładowanie 100%")
    time.sleep(0.5)
    print("już prawie to mamy , zostało jedynie ściągnięcie danych z servera!!!")

    time.sleep(2)

    print("Ściąganie danych 10%")
    time.sleep(0.5)
    print("Ściąganie danych 20%")
    time.sleep(0.5)
    print("Ściąganie danych 30%")
    time.sleep(0.5)
    print("Ściąganie danych 40%")
    time.sleep(0.5)
    print("Ściąganie danych 50%")
    time.sleep(0.5)
    print("Ściąganie danych 60%")
    time.sleep(0.5)
    print("Ściąganie danych 70%")
    time.sleep(0.5)
    print("Ściąganie danych 80%")
    time.sleep(0.5)
    print("Ściąganie danych 90%")
    time.sleep(0.5)
    print("Ściąganie danych 100%")
    time.sleep(0.5)
    print("skończone , aktualna pogoda w twoim miejscu to...")
    time.sleep(2)
    print("idk zajrzyj za okno czy coś xddd")